[package]
name = "esp_ward"
version = "0.1.0"
authors = ["Kirill Mikhailov <playfulfence@gmail.com>"]
edition = "2021"

[profile.release]
debug = true

[dependencies]
hal = { package = "esp32c3-hal", version = "0.10.0", features = ["async", "embassy-time-timg0"] }
esp-backtrace = { version = "0.7.0", features = ["esp32c3", "panic-handler", "exception-handler", "print-uart"] }
esp-println       = { version = "0.8.0", features = ["esp32c3", "log"] }