[package]
name = "esp_ward"
version = "0.1.0"
authors = ["Kirill Mikhailov <playfulfence@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.release]
debug = true

[dependencies]
hal = { package = "esp32c3-hal", version = "0.10.0", features = ["async", "embassy-time-timg0"] }
esp-backtrace = { version = "0.7.0", features = ["esp32c3", "panic-handler", "exception-handler", "print-uart"] }
esp-println       = { version = "0.5.0", features = ["esp32c3", "log"] }

esp-wifi = { git = "https://github.com/esp-rs/esp-wifi", rev = "68dc11bbb2c0efa29c4acbbf134d6f142441065e", features = ["esp32c3", "async", "embassy-net", "embedded-svc", "wifi", "ipv6"] }
smoltcp = { version = "0.10.0", default-features=false, features = ["proto-igmp", "proto-ipv4", "socket-tcp", "socket-icmp", "socket-udp", "medium-ethernet", "proto-dhcpv4", "socket-raw", "socket-dhcpv4"] }
embedded-svc = { version = "0.25.0", default-features = false}
log = "0.4.17"

no-std-net = "0.6"
heapless = "0.7.16"

critical-section = "1.1.1"

rs-matter = { git = "https://github.com/ivmarkov/matter-rs", default-features = false, features = ["rustcrypto", "embassy-net"] }
# would be nice to not need it - however there are allocations made in RustCrypto (apparently even beyond what the X509 handling does)
esp-alloc = { version = "0.3.0"}

portable-atomic = { version = "1", default-features = false, features = ["critical-section","require-cas"] }
embassy-executor = { version = "0.2.0", package = "embassy-executor", features = ["nightly", "executor-thread", "integrated-timers", "arch-riscv32"] }
embassy-time = { version = "0.1.1", features = ["nightly"] }
futures-util = { version = "0.3.17", default-features = false }
embassy-futures = { version = "0.1.0" }
embassy-net = { version = "0.1.0", features = ["nightly", "tcp", "udp", "dhcpv4", "medium-ethernet", "proto-ipv6", "log"] }
embedded-io = { version = "0.4.0" }
embassy-sync = { version = "0.2.0" }
static_cell = { version = "1.1", features = ["nightly"]}

[patch.crates-io]
embassy-net = { git = "https://github.com/embassy-rs/embassy", rev = "3382ca1a5429504c56c360e99ec09f4f641948a2"}
embassy-net-driver = { git = "https://github.com/embassy-rs/embassy", rev = "3382ca1a5429504c56c360e99ec09f4f641948a2"}
