# Code formatting settings are copied from esp-hal/rustfmt.toml format configuration file
# Availavble on: https://github.com/esp-rs/esp-hal/blob/main/rustfmt.toml

# Comments
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true

# Enums
enum_discrim_align_threshold = 35

# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
