[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
   "-C", "link-arg=-Trom_functions.x",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core", "alloc"]