[target.riscv32imc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "force-frame-pointers"]

[target.riscv32imac-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "force-frame-pointers"]

[target.xtensa-esp32-none-elf]
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.xtensa-esp32s3-none-elf]
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[target.xtensa-esp32s2-none-elf]
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "force-frame-pointers"]

[unstable]
build-std = ["core", "alloc"]
